---
apiVersion: v1
data:
  cluster.name: your-cluster-name
  logs.region: your-cluster-region
  # The below configuration file is in JSON format.
  # Please ensure you keep it well-formed if you modify it.
  cluster-info.json: |
    {
      "cluster": {
        "name": "your-cluster-name"
      },
      "logs": {
        "region": "your-cluster-region"
      }
    }
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: amazon-cloudwatch
